export class UpdateCartographieDitwDto {
  class_id: string;
  server_group: string
  application: string
  environment: string
  socle: string
  tag: string
  internal_port: string
  url: string
  path_version: string
  maven_id: string
  jenkins_folders: string
  jira_url: string
  sr_component: string
  vip_server: string
  vip_db: string
  server_web_lan: string
  server_web_dmz: string
  server_db: string
  lien_applications: string
  version_db: string
  version_os: string
  version_apache: string
  server_applicatif: string
  language: string
  framework: string
  framework_2: string
  eol_stack: string
  eol_db: string
  eol_apache: string
  eol_server_applicatif: string
  eol_framework: string
  eol_framework_2: string
  cible_db: string
  cible_os_server: string
  cible_apache: string
  cible_server_applicatif: string
  cible_language: string
  cible_framework: string
  cible_framework_2: string
  eol_cible_db: string
  eol_cible_os_server: string
  eol_cible_apache: string
  eol_cible_server_applicatif: string
  eol_cible_language: string
  eol_cible_framework: string
  eol_cible_framework_2: string
  vcpu: string
  ram: string
  disque: string
  db_vcpu: string
  db_ram: string
  db_disque: string
}
